return {
	{
		"nvim-treesitter/nvim-treesitter",
		build = ":TSUpdate",
		opts = {
			ensure_installed = {
				"bash",
				"cooklang",
				"diff",
				"dockerfile",
				"editorconfig",
				"elixir",
				"erlang",
				"gitignore",
				"gleam",
				"go",
				"haskell",
				"html",
				"java",
				"javascript",
				"jsdoc",
				"json",
				"json5",
				"jsonc",
				"lua",
				"luadoc",
				"markdown",
				"markdown_inline",
				"nim",
				"nim_format_string",
				"ocaml",
				"ocaml_interface",
				"python",
				"query",
				"regex",
				"rust",
				"scss",
				"sql",
				"styled",
				"toml",
				"tsx",
				"typescript",
				"vim",
				"vimdoc",
				"vue",
				"xml",
				"yaml",
				"zig",
			},
			auto_install = true,
			highlight = {
				enable = true,
				additional_vim_regex_highlighting = { "ruby" },
			},
			indent = { enable = true, disable = { "ruby" } },
		},
		config = function(_, opts)
			require("nvim-treesitter.configs").setup(opts)
			require("treesitter-context").setup({ max_lines = 10, multiline_threshold = 5 })
		end,
	},
	{ "nvim-treesitter/nvim-treesitter-context" },
}
